#!/bin/bash

yum -y install http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
yum -y install salt-minion --enablerepo=epel-testing

cat << EOM > /etc/salt/grains
hdfs_data_disks:
  - /disk2
  - /disk3

mapred_data_disks:
  - /disk2
  - /disk3

yarn_data_disks:
  - /disk2
  - /disk3

roles:
  - hadoop_master
  - accumulo_master
  - accumulo_proxy
  - development
  - monitor

EOM

curl http://10.106.140.216/grains.deku >> /etc/salt/grains

cat << EOM > /etc/salt/minion
# startup-provisioned
master: 10.106.140.216

mine_functions:
  network.interfaces: []
  test.ping: []
  grains.items: []
  network.ip_addrs:
    - bond0

mine_interval: 2

EOM

service salt-minion restart
chkconfig salt-minion on

dev="/dev/sdb"
partition="${dev}1"
label="applogs"
mountpoint="/${label}"
echo -n "Looking for $dev "

if [ -b $dev ]
then
  echo "... found"
  if [ ! -b $partition ]
  then
    echo "Partitioning $dev"
    parted ${dev} --script -- mklabel ${label}
    parted ${dev} --script -- mkpart primary 0 -1
  else
    echo "Partition ${partition} already exists"
  fi

  echo "Formatting partition $partition"
  mkfs.ext3 $partition

  echo "Labeling partition $partition as $label"
  e2label $partition $label

  echo "Mounting partition $partition to $mountpoint"
  [ ! -d $mountpoint ] && mkdir $mountpoint

  if [ $(grep -c $mountpoint /etc/mtab) -eq 0 ]
  then
    mount LABEL=$label -o noatime $mountpoint
  fi

  if [ $(grep -c $mountpoint /etc/mtab) -ne 0 ]
  then
    echo "$partition is mounted on $mountpoint"
  else
    echo "$partition is not mounted"
  fi

  if [ $(grep -c $mountpoint /etc/fstab) -eq 0 ]
  then
    echo "Adding $partition to /etc/fstab"
    grep $mountpoint /etc/mtab >> /etc/fstab
  fi
else
  echo "... not found"
fi

i=1
for n in c d e f
do
    dev="/dev/sd${n}"
    partition="${dev}1"
    label="disk${i}"
    mountpoint="/${label}"
    echo -n "Looking for $dev "

    if [ -b $dev ]
    then
      echo "... found"
      if [ ! -b $partition ]
      then
        echo "Partitioning $dev"
        parted ${dev} --script -- mklabel ${label}
        parted ${dev} --script -- mkpart primary 0 -1
      else
        echo "Partition ${partition} already exists"
      fi

      echo "Formatting partition $partition"
      mkfs.ext3 $partition

      echo "Labeling partition $partition as $label"
      e2label $partition $label

      echo "Mounting partition $partition to $mountpoint"
      [ ! -d $mountpoint ] && mkdir $mountpoint

      if [ $(grep -c $mountpoint /etc/mtab) -eq 0 ]
      then
        mount LABEL=$label -o noatime $mountpoint
      fi

      if [ $(grep -c $mountpoint /etc/mtab) -ne 0 ]
      then
        echo "$partition is mounted on $mountpoint"
      else
        echo "$partition is not mounted"
      fi

      if [ $(grep -c $mountpoint /etc/fstab) -eq 0 ]
      then
        echo "Adding $partition to /etc/fstab"
        grep $mountpoint /etc/mtab >> /etc/fstab
      fi
    else
      echo "... not found"
    fi

    let i=${i}+1
done
