#!/bin/bash

yum -y install http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
yum -y install salt-minion --enablerepo=epel-testing

cat << EOM > /etc/salt/grains
hdfs_data_disks:
  - /disk2
  - /disk3

mapred_data_disks:
  - /disk2
  - /disk3

yarn_data_disks:
  - /disk2
  - /disk3

roles:
  - hadoop_master
  - accumulo_master
  - accumulo_proxy
  - development
  - monitor

EOM

curl http://10.106.140.216/grains.deku >> /etc/salt/grains

cat << EOM > /etc/salt/minion
# startup-provisioned
master: 10.106.140.216

mine_functions:
  network.interfaces: []
  test.ping: []
  grains.items: []
  network.ip_addrs:
    - bond0

mine_interval: 2

EOM

service salt-minion restart
chkconfig salt-minion on

[ -d /disk1 -a ! -d /applogs ] && ln -s /disk1 /applogs
for a in 1 2 3 4 5 6 7 8 9
do
  [ -d /disk${q} ] && rm -rvf /disk${a}/*
done

